overrides:
  esbuild: ">=0.25.0"

ignoredBuiltDependencies:
  - "@esbuild-kit/core-utils"
  - "@esbuild-kit/esm-loader"
  - prebuild-install
  - unrs-resolver

allowBuilds:
  better-sqlite3: true
  esbuild: true
  sharp: true
