server {
    listen 80;
    listen [::]:80;
    server_name cdn.casalnovidades.com;
    return 301 https://cdn.casalnovidades.com$request_uri;
}

# server {
#   listen 443 ssl;
#   listen [::]:443 ssl;

#   ssl_certificate         /etc/letsencrypt/live/casalnovidades.com/fullchain.pem;
#   ssl_certificate_key     /etc/letsencrypt/live/casalnovidades.com/privkey.pem;

#   server_name cdn.casalnovidades.com;

#   location ~* .(gif|jpg|jpeg|png|avi|mpg|mpeg|mp4|htm|html|js|css|mp3|ico|flv)$ {
#     expires max;
#     proxy_set_header  X-Real-IP  $remote_addr;
#     proxy_pass https://cdn.casalnovidades.com;
#     proxy_ignore_headers X-Accel-Expires Expires Cache-Control;
#     proxy_store /var/www/cache$uri;
#     proxy_store_access user:rw group:rw all:r;
#   }
# }

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    ssl_certificate         /etc/letsencrypt/live/casalnovidades.com/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/casalnovidades.com/privkey.pem;

    server_name cdn.casalnovidades.com;
    root /var/www/cdn.casalnovidades.com;

    include conf.d/cn-errors.conf;

    location ~* \.(jpg|jpeg|png|gif|webm|webp|css|mp4|mp3|wav|swf|mov|doc|pdf|xls|ppt|docx|pptx|xlsx|eot|ttf|woff|woff2)$ {
        add_header Access-Control-Allow-Origin *;
        expires 90d; # max
        gzip on;
        gzip_types *;
    }
    
    location ~ /\. { deny all; }
    location ~ ~$ { deny all; }
    location ~ \.php$ { deny all; }
}
