#include conf.d/nuxt.map;

server {
    listen 80;
    listen [::]:80;
    server_name casalnovidades.com *.casalnovidades.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    ssl_certificate         /etc/letsencrypt/live/casalnovidades.com/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/casalnovidades.com/privkey.pem;

    server_name www.casalnovidades.com;

    return 301 https://casalnovidades.com$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    ssl_certificate         /etc/letsencrypt/live/casalnovidades.com/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/casalnovidades.com/privkey.pem;

    server_name casalnovidades.com *.casalnovidades.com;
    root /var/www/casalnovidades.com;

    #location /whatsapp { return 301 https://chat.whatsapp.com/FjJqPtI1keX5ZnsN9LdNT2; }

    #include conf.d/errors.conf;
    include conf.d/static.conf;
    include conf.d/deny.conf;
}
