# path: /etc/nginx/sites-available/cdn.privatehub.com.br
# https://gist.github.com/alsyundawy/5b54f8c6023ffbdc5af272d09c51e9c2
# https://github.com/lalizita/nginx-cache
# https://dev.to/janreges/how-to-build-a-cdn-23-server-and-reverse-proxy-configuration-16md

server {
    listen 80;
    listen [::]:80;
    server_name cdn.privatehub.com.br;
    return 301 https://cdn.privatehub.com.br$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    ssl_certificate         /etc/letsencrypt/live/privatehub.com.br/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/privatehub.com.br/privkey.pem;

    server_name cdn.privatehub.com.br;
    root /var/www/cdn.privatehub.com.br;

    include conf.d/ph-errors.conf;

    location ~* .(mp4|jpg|jpeg|png|gif|webp|css|mp3|wav|swf|mov|doc|pdf|xls|ppt|docx|pptx|xlsx)$ {
        expires 90d; # max
        gzip on;
        gzip_types *;
    }
    
    location ~ /\. { deny all; }
    location ~ ~$ { deny all; }
    location ~ \.php$ { deny all; }
}
