# path: /etc/nginx/sites-available/privatehub.com.br

server {
    listen 80;
    listen [::]:80;
    server_name *.privatehub.com.br privatehub.com.br;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    ssl_certificate         /etc/letsencrypt/live/privatehub.com.br/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/privatehub.com.br/privkey.pem;

    server_name www.privatehub.com.br;
    return 301 https://privatehub.com.br$request_uri;
}

# server {
#     listen 443 ssl;
#     listen [::]:443 ssl;

#     ssl_certificate         /etc/letsencrypt/live/privatehub.com.br/fullchain.pem;
#     ssl_certificate_key     /etc/letsencrypt/live/privatehub.com.br/privkey.pem;

#     server_name ~^(?<subdomain>[^.]+).privatehub.com.br;
#     root /var/www/privatehub/frontend/dist;

#     include conf.d/cache.conf;
#     include conf.d/errors.conf;

#     location / {
#         try_files $uri $uri/ /index.html?subdomain=$subdomain =500;
#     }
# }

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    ssl_certificate         /etc/letsencrypt/live/privatehub.com.br/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/privatehub.com.br/privkey.pem;

    #server_name privatehub.com.br *.privatehub.com.br;
    server_name privatehub.com.br;

    root /var/www/privatehub/frontend/dist;

    #include conf.d/cache.conf;
    include conf.d/ph-errors.conf;

    location / {
        try_files $uri $uri/ /index.html =500;
    }
}
