name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Add Bun to PATH
      shell: bash
      run: |
        echo "/home/nginx/.bun/bin" >> $GITHUB_PATH
    - name: Deploy using SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASS }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ${{ secrets.PROJECT_PATH }}
          git pull origin main
          bun install
          bun run build
